Handling of unequal subgroup sizes in subgroup charts
jasp-stats/jaspQualityControl pull request #237
Opened 2023-03-20 15:35 UTC by JTPetter

Functionality to handle unequal subgroup sizes in subgroup charts. Required quite some rewriting (to actually create groups by subgroup variable for instance) and hand calculation for many things.

2023-03-20 15:59 UTC, JTPetter commented
Also, many unit test files are changed because `geom_step` looks slightly different than `geom_hline`

2023-04-12 07:39 UTC, vandenman requested changes

2023-04-16 09:51 UTC, JTPetter commented on inst/qml/variablesChartsSubgroups.qml
> +			name:								"axisLabels"
It only looks like I changed the name, subgroups is actually still there on lines 44-53

2023-04-18 09:42 UTC, vandenman approved these changes

2023-04-18 09:42 UTC, merged