Fixing various bugs
jasp-stats/jaspQualityControl pull request #254
Opened 2023-06-06 14:28 UTC by JTPetter

- Linearity Study: Added sensible error message when only one observation per part.
- Individual Charts: Added sensible error message when moving range length was larger than one of the subgroups.
- Individual Charts: Fix crashes of IMR chart when moving range length is equal to data/stage length.

2023-06-07 15:47 UTC, JTPetter commented
Interestingly the unit tests worked for [edd893a](https://github.com/jasp-stats/jaspQualityControl/pull/254/commits/edd893a9fe577faf8a3d9b92a9965bb739cf1340), but not anymore for [ce2b4bd](https://github.com/jasp-stats/jaspQualityControl/pull/254/commits/ce2b4bde4e5ec09b1c2f1048cfd76e78cacb9bba), although I really don't see what could have caused them to fail in this change?

2023-06-07 16:27 UTC, JTPetter commented
... and somehow my new commits to https://github.com/JTPetter/jaspQualityControl/tree/fixingVariousBugs don't show up in this PR anymore?

2023-06-08 08:23 UTC, vandenman requested changes

2023-06-08 08:23 UTC, vandenman commented on R/msaGaugeRRnonrep.R
> +  index <- sequence(plyr::count(dataset, vars = c(parts, operators))$freq)
Can this use `dplyr::count` instead? `plyr` is retired so it's probably better to use `dplyr` or another package instead.

2023-06-08 08:23 UTC, vandenman commented on R/msaGaugeLinearity.R
> +      table2$setError(gettextf("T-Test requires more than 1 measurement in total. %i valid measurement(s) detected in %s.", length(dataset[[measurements]]), measurements))
```suggestion
      table2$setError(gettextf("T-Test requires more than 1 measurement in total. %1$i valid measurement(s) detected in %2$s.", length(dataset[[measurements]]), measurements))
```

2023-06-08 08:23 UTC, vandenman commented on R/msaGaugeLinearity.R
>        table2$setError(gettextf("Every unique part must have one corresponding reference value. %i reference values were found for %s unique parts.", length(unique(dataset[[standards]])), length(uniqu
same as the above, use `%$1x` and `%$2x`.

2023-06-13 14:54 UTC, JTPetter commented
@vandenman Thank you, I addressed your comments.

2023-06-16 14:46 UTC, merged